import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {existsSync,statSync,readFileSync} from 'node:fs';
import {resolve,dirname} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';

if(!process.env.KN_PROJECT)throw Error('Set KN_PROJECT to the DSH checkout used to build the plugin.');
const root=resolve(process.env.KN_PROJECT).replace(/\\/g,'/');
const pluginRoot=fileURLToPath(new URL('../',import.meta.url)).replace(/\\/g,'/').replace(/\/$/,'');
const {rolldown}=await import(pathToFileURL(root+'/node_modules/.pnpm/rolldown@1.0.3/node_modules/rolldown/dist/index.mjs').href);
const {chromium}=await import(pathToFileURL(root+'/node_modules/.pnpm/playwright@1.61.1/node_modules/playwright/index.mjs').href);
const require=createRequire(root+'/package.json');
const ts=require('typescript');const paths=ts.readConfigFile(root+'/tsconfig.base.json',ts.sys.readFile).config.compilerOptions.paths;
const entry=`import React from 'react';import * as ReactDOM from 'react-dom';import * as JSX from 'react/jsx-runtime';import{createRoot}from'react-dom/client';
import{NodeConversations}from'${pluginRoot}/src/client/NodeConversations.tsx';
import{attachConversationServices,nodeConversations}from'${pluginRoot}/src/client/node-conversations.ts';
import{createSidebarRightController}from'${root}/packages/client/ui-sidebar-right/src/client/service.ts';
import{SidebarRightTabRegistry}from'${root}/packages/client/ui-sidebar-right/src/client/tab-registry.ts';
import{createSidebarRightStore}from'${root}/packages/client/ui-sidebar-right/src/client/stores.ts';
const registry=new SidebarRightTabRegistry({effect:fn=>fn()});for(const kind of ['guide','knowledgenet','browser'])registry.register({id:kind,kind,multiple:kind==='browser',title:()=>kind});registry.register({id:'document',kind:'document',patterns:['dsh-resource://file/**'],title:()=> '文档'});
const {controller,adopt}=createSidebarRightController(registry,()=>{});const stores=new Map();const store=id=>{if(!stores.has(id)){const value=createSidebarRightStore(()=>({kind:'guide',title:'guide'})).create();stores.set(id,value);adopt(id,value);}return stores.get(id);};let release=()=>{};function bind(id){release();const value=store(id);release=controller.bind({sessionId:id,actions:value.actions,surfaces:value.getSnapshot().bySession,closeWithFocus:(p,fn)=>fn(),openWithFocus:fn=>fn(),canSplitPane:()=>true});}
bind('old');controller.openTab('knowledgenet',{params:{root:'library'}});controller.openTab('browser',{params:{url:'https://example.com'}});controller.openResource('dsh-resource://file/report.md',{params:{line:12}});controller.focus(controller.tabsIn('old').find(t=>t.kind==='knowledgenet').id);
window.__ModuleLoader__={load:({factory})=>{window.plugin=factory(name=>({'react':React,'react-dom':ReactDOM,'react/jsx-runtime':JSX}[name]));}};
window.mountNote=()=>{window.plugin.attachConversationServices(()=>({sessions:{create:async()=>'chat-1',list:{getSnapshot:()=>({byId:{'chat-1':{blank:false,title:'历史对话'}}})}},uiWorkspace:{openSession:()=>{}}}));const node=document.createElement('div');document.body.appendChild(node);const noteRoot=createRoot(node);const fetcher=async()=>({json:async()=>({ok:true,document:{nodeId:'node-a',title:'笔记',path:'Nodes/a.md',text:'正文',hash:'hash',revision:1}})});noteRoot.render(React.createElement(window.plugin.NodeDocumentEditor,{nodeId:'node-a',libraryKey:'library',target:{root:'library'},fetcher,onClose:()=>{},onOpenConversation:()=>{window.cachedAtNavigation=window.plugin.recallDraft(window.plugin.draftKey('library','node-a'));noteRoot.unmount();}}));};
window.records=[];window.opened=[];const sessionListeners=new Set();const workspaceListeners=new Set();window.summary={phase:'ready',byId:{'chat-1':{blank:true,displayTitle:'新对话'}}};window.workspace={archivedSessionIds:[]};window.fetch=async(url,options)=>{const body=JSON.parse(options.body);if(body.kind==='record-node-conversation')window.records.push({sessionId:body.conversationId,createdAt:Date.now()});return{ok:true,json:async()=>({ok:true,root:'library',cwd:'/workspace',conversations:window.records})};};
attachConversationServices(()=>({sessions:{create:async()=>'chat-1',list:{getSnapshot:()=>window.summary,subscribe:fn=>{sessionListeners.add(fn);return()=>sessionListeners.delete(fn);}}},workspaces:{list:{getSnapshot:()=>window.workspace,subscribe:fn=>{workspaceListeners.add(fn);return()=>workspaceListeners.delete(fn);}}},uiWorkspace:{openSession:id=>{window.opened.push(id);release();setTimeout(()=>bind(id),100);}},sidebarRight:controller}));
window.startChat=()=>{window.summary={phase:'ready',byId:{'chat-1':{blank:false,title:'第一轮标题'}}};for(const fn of sessionListeners)fn();};window.renameChat=()=>{window.summary.byId['chat-1'].title='更新后的标题';for(const fn of sessionListeners)fn();};window.archiveChat=()=>{window.workspace.archivedSessionIds=['chat-1'];for(const fn of workspaceListeners)fn();};
window.sidebarResult=()=>({mounted:controller.mounted.getSnapshot(),expanded:controller.isExpanded(),tabs:controller.tabsIn('chat-1').map(t=>({kind:t.kind,params:controller.tabDomain.occurrence('chat-1',t).navigation.getSnapshot().params})),old:controller.tabsIn('old').map(t=>t.kind),active:controller.active()?.kind});window.actions=nodeConversations;
const pickerRoot=createRoot(document.getElementById('app'));window.unmountPicker=()=>pickerRoot.unmount();window.prepareSlowCreation=()=>attachConversationServices(()=>({sessions:{create:()=>new Promise(resolve=>{window.finishCreation=()=>resolve('chat-2');}),list:{getSnapshot:()=>({phase:'ready',byId:{'chat-1':{blank:false},'chat-2':{blank:false}}})}},uiWorkspace:{openSession:id=>window.opened.push(id)}}));pickerRoot.render(React.createElement(NodeConversations,{nodeId:'node-a',target:{root:'library'},onOpen:id=>nodeConversations.open(id)}));`;
const build=await rolldown({input:'virtual:entry',plugins:[{name:'local',resolveId(id,importer){if(id==='virtual:entry')return id;if(['react','react-dom','react-dom/client','react/jsx-runtime'].includes(id))return createRequire(root+'/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/package.json').resolve(id);if(paths[id]){let file=resolve(root,paths[id][0]);if(existsSync(file)&&statSync(file).isDirectory())file=resolve(file,'index.ts');return file;}if(!id.startsWith('.')&&!id.includes(':/')){try{return createRequire(importer&&importer!=='virtual:entry'?importer:root+'/packages/client/ui-sidebar-right/package.json').resolve(id);}catch{try{return require.resolve(id);}catch{}}}},load(id){if(id==='virtual:entry')return entry;if(id.endsWith('.css'))return {code:'export default {}',moduleType:'js'};}}]});
const output=await build.generate({format:'iife'});await build.close();const code=output.output.find(o=>o.type==='chunk').code;
const compiled=readFileSync(pluginRoot+'/client.js','utf8').replace('exports.apply = apply;','exports.apply = apply; exports.NodeDocumentEditor = NodeDocumentEditor; exports.recallDraft = recallDraft; exports.draftKey = draftKey; exports.attachConversationServices = attachConversationServices;');
const server=createServer((request,response)=>{response.setHeader('Content-Type',request.url.endsWith('.js')?'text/javascript; charset=utf-8':'text/html; charset=utf-8');response.end(request.url==='/app.js'?code:request.url==='/plugin.js'?compiled:'<!doctype html><meta charset="utf-8"><div id="app"></div><script src="/app.js"></script><script src="/plugin.js"></script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.KN_CHROME ?? 'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.getByRole('button',{name:'对话 0',exact:true}).click();await page.getByRole('button',{name:'打开新对话',exact:true}).click();await page.waitForFunction(()=>window.sidebarResult().mounted==='chat-1');const side=await page.evaluate(()=>window.sidebarResult());if(!side.expanded||side.active!=='knowledgenet'||!['knowledgenet','browser','document'].every(k=>side.tabs.some(t=>t.kind===k))||!side.tabs.some(t=>t.kind==='browser'&&t.params.url==='https://example.com'))throw Error(JSON.stringify(side));await page.evaluate(()=>window.startChat());await page.getByRole('button',{name:'对话 1',exact:true}).waitFor();await page.getByRole('button',{name:'对话 1',exact:true}).click();await page.getByRole('button',{name:/第一轮标题/}).waitFor();await page.evaluate(()=>window.renameChat());await page.getByRole('button',{name:/更新后的标题/}).waitFor();await page.evaluate(()=>window.archiveChat());await page.getByRole('button',{name:'对话 0',exact:true}).waitFor();await page.evaluate(()=>window.mountNote());const editor=page.locator('.kn-editor .ProseMirror');await editor.waitFor();await editor.click();await page.keyboard.press('End');await page.keyboard.insertText('最后输入');await page.locator('.kn-editor').getByRole('button',{name:'对话 1',exact:true}).click();await page.locator('.kn-editor').getByRole('button',{name:/历史对话/}).click();const draft=await page.evaluate(()=>window.cachedAtNavigation);if(!draft?.draft.includes('最后输入'))throw Error('切换前草稿没有最新输入：'+JSON.stringify(draft));await page.evaluate(()=>window.prepareSlowCreation());const picker=page.locator('#app');const create=picker.getByRole('button',{name:'打开新对话',exact:true});if(!await create.isVisible())await picker.getByRole('button',{name:'对话 1',exact:true}).click();await create.click();await page.waitForFunction(()=>typeof window.finishCreation==='function');const before=await page.evaluate(()=>window.opened.length);await page.evaluate(()=>{window.unmountPicker();window.finishCreation();});await page.waitForFunction(()=>window.records.some(record=>record.sessionId==='chat-2'));await page.evaluate(()=>Promise.resolve());if(await page.evaluate(()=>window.opened.length)!==before)throw Error('卸载后仍发生跳转');if(errors.length)throw Error(errors.join('\n'));console.log('浏览器通过：真实 DSH 侧栏控制器恢复图谱、浏览器、文档标签与导航参数；首次消息、改名、归档实时更新，最新富文本输入在切换前同步缓存，组件卸载后迟到创建不再跳转，无运行时错误。');}finally{await browser.close();await new Promise(r=>server.close(r));}
