import {createServer} from 'node:http';
import {createRequire} from 'node:module';
import {readFileSync} from 'node:fs';
import {pathToFileURL} from 'node:url';
const project=process.env.KN_PROJECT;if(!project)throw Error('Set KN_PROJECT.');
const {rolldown}=await import(pathToFileURL(project+'/node_modules/.pnpm/rolldown@1.0.3/node_modules/rolldown/dist/index.mjs'));
const {chromium}=await import(pathToFileURL(project+'/node_modules/.pnpm/playwright@1.61.1/node_modules/playwright/index.mjs'));
const req=createRequire(project+'/node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/package.json');
const entry=`import React from 'react';import * as ReactDOM from 'react-dom';import * as JSX from 'react/jsx-runtime';import {createRoot} from 'react-dom/client';window.__ModuleLoader__={load:({factory})=>{window.plugin=factory(name=>({'react':React,'react-dom':ReactDOM,'react/jsx-runtime':JSX}[name]));}};const root=createRoot(document.getElementById('app'));let sequence=0;window.mount=(markdown)=>{window.handle=React.createRef();root.render(React.createElement(window.plugin.MarkdownRichEditor,{key:++sequence,markdown,readOnly:false,handleRef:window.handle,report:(step,detail)=>{(window.reports??=[]).push({step,detail});},onChange:value=>window.markdown=value}));};`;
const build=await rolldown({input:'entry',plugins:[{name:'test',resolveId(id){if(id==='entry')return id;try{return req.resolve(id);}catch{}},load(id){if(id==='entry')return entry;}}]});const {output}=await build.generate({format:'iife'});await build.close();
const code=output.find(item=>item.type==='chunk').code;
const compiled=readFileSync(new URL('../client.js',import.meta.url),'utf8').replace('exports.apply = apply;','exports.apply = apply; exports.MarkdownRichEditor = MarkdownRichEditor;');
const server=createServer((request,response)=>{response.setHeader('Content-Type',request.url.endsWith('.js')?'text/javascript':'text/html');response.end(request.url==='/app.js'?code:request.url==='/plugin.js'?compiled:'<!doctype html><meta charset="utf-8"><style>body{margin:20px}.kn-editor-rich{height:650px;overflow:auto}.milkdown{min-height:300px}</style><div id="app"></div><script src="/app.js"></script><script src="/plugin.js"></script>');});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.KN_CHROME??'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);
 const mount=async markdown=>{await page.evaluate(value=>window.mount(value),markdown);await page.waitForFunction(()=>window.handle?.current?.isReady());};
 const menu=page.locator('.milkdown-slash-menu[data-show="true"]');
 for(const [markdown,selector] of [['普通正文','p'],['- 第一项\n- 第二项\n- 第三项','li p'],['> 引用正文','blockquote p'],['# 标题正文','h1']]){
  await mount(markdown);await page.locator('.ProseMirror '+selector).last().click();await page.keyboard.press('Home');await page.keyboard.type('/');await menu.waitFor({state:'visible',timeout:5000}).catch(async error=>{throw Error(error.message+' diagnostics '+JSON.stringify(await page.evaluate(()=>({reports:window.reports?.slice(-8),menus:[...document.querySelectorAll('.milkdown-slash-menu')].map(e=>({show:e.dataset.show,rect:e.getBoundingClientRect().toJSON(),text:e.innerText.slice(0,80)}))}))));});await page.keyboard.press('Escape');const text=await page.evaluate(()=>window.handle.current.flush());if(text.includes('/'))throw Error('取消菜单留下斜杠');
 }
 await mount('- 第一项\n- 最后一项');await page.locator('.ProseMirror li p').last().click();await page.keyboard.press('Home');await page.keyboard.press('Shift+End');await page.keyboard.press('Backspace');await page.keyboard.type('/');await menu.waitFor({state:'visible'});await page.keyboard.press('Escape');
 await mount('- 原有前文 后文');const list=page.locator('.ProseMirror li p');await list.click();await page.keyboard.press('Home');for(let i=0;i<5;i++)await page.keyboard.press('ArrowRight');await page.keyboard.type('/');await menu.waitFor({state:'visible'});await page.keyboard.type('Table');await page.waitForFunction(()=>document.querySelectorAll('.milkdown-slash-menu[data-show="true"] .menu-groups li').length===1,{},{timeout:5000}).catch(async error=>{throw Error(error.message+' filter diagnostics '+JSON.stringify(await page.evaluate(()=>({markdown:window.handle.current.flush(),reports:window.reports?.slice(-5),menus:[...document.querySelectorAll('.milkdown-slash-menu')].map(e=>({show:e.dataset.show,text:e.textContent.slice(0,400)}))}))));});await menu.getByText('Table',{exact:true}).click();await page.locator('.ProseMirror table.children').waitFor();const inserted=await page.evaluate(()=>window.handle.current.flush());if(!inserted.includes('原有前文')||!inserted.includes('后文')||inserted.includes('Table'))throw Error('插入表格损坏原文：'+inserted);
 await mount('https:');await page.locator('.ProseMirror p').click();await page.keyboard.press('End');await page.keyboard.type('/');if(await menu.count())throw Error('网址误弹菜单');await page.waitForFunction(()=>document.querySelector('.ProseMirror')?.innerText==='https:/',{},{timeout:3000}).catch(async error=>{throw Error('普通斜杠 '+JSON.stringify(await page.evaluate(()=>({md:window.handle.current.flush(),dom:document.querySelector('.ProseMirror')?.innerText}))));});
 await mount('前文 后文');await page.locator('.ProseMirror p').click();await page.keyboard.press('Home');for(let i=0;i<3;i++)await page.keyboard.press('ArrowRight');await page.keyboard.type('/');await menu.waitFor({state:'visible'});await page.keyboard.type('Heading 2');await page.waitForFunction(()=>document.querySelectorAll('.milkdown-slash-menu[data-show="true"] .menu-groups li').length===1);await menu.getByText('Heading 2',{exact:true}).click();const heading=await page.evaluate(()=>window.handle.current.flush());if(!heading.includes('前文')||!heading.includes('后文'))throw Error('已有文字丢失：'+heading);
 if(errors.length)throw Error(errors.join('\n'));console.log('浏览器通过：正文、列表、引用、标题唤起；筛选并插入表格/标题保留前后正文；Escape 取消；网址保留斜杠，无运行时异常。');
}finally{await browser.close();await new Promise(r=>server.close(r));}
