import assert from 'node:assert/strict';
import {test} from 'node:test';
import {readFile} from 'node:fs/promises';
import {Schema} from '@milkdown/kit/prose/model';
import {EditorState,TextSelection} from '@milkdown/kit/prose/state';
import {shouldOpenSlashMenu,prepareSlashInsertion,readSlashMenuApi} from '../src/client/slash-menu.ts';
import {patchCrepeSlashMenu} from '../scripts/slash-menu-patch.mjs';
const schema=new Schema({nodes:{doc:{content:'block+'},paragraph:{group:'block',content:'text*'},heading:{group:'block',content:'text*'},blockquote:{group:'block',content:'block+'},bullet_list:{group:'block',content:'list_item+'},list_item:{content:'paragraph block*'},code_block:{group:'block',content:'text*'},table_cell:{group:'block',content:'paragraph+'},text:{}},marks:{code:{},link:{attrs:{href:{default:''}}}}});
const p=text=>schema.node('paragraph',null,text?schema.text(text):null);
function state(node,offset=0){const doc=schema.node('doc',null,node);let pos;doc.descendants((n,at)=>{if(pos===undefined&&n.isTextblock)pos=at+1;});return EditorState.create({doc,selection:TextSelection.create(doc,pos+offset)});}
test('空段落、列表、引用、标题及已有文字段首均可唤起',()=>{for(const node of [p(''),p('已有文字'),schema.node('heading',null,schema.text('标题')),schema.node('bullet_list',null,schema.node('list_item',null,p(''))),schema.node('blockquote',null,p(''))])assert.equal(shouldOpenSlashMenu(state(node)),state(node).selection.from);});
test('空格后与中文后可唤起；网址、路径、代码、表格及范围选择保留普通斜杠输入',()=>{assert.notEqual(shouldOpenSlashMenu(state(p('已有文字 '),5)),null);assert.notEqual(shouldOpenSlashMenu(state(p('已有文字'),4)),null);for(const text of ['https:','https://网址','路径/目录','path','C:\\dir','a'])assert.equal(shouldOpenSlashMenu(state(p(text),text.length)),null);for(const node of [schema.node('code_block'),schema.node('table_cell',null,p('')),p('code').mark([])]){if(node.type.name==='paragraph')continue;assert.equal(shouldOpenSlashMenu(state(node)),null);}const doc=schema.node('doc',null,p('abc'));assert.equal(shouldOpenSlashMenu(EditorState.create({doc,selection:TextSelection.create(doc,1,2)})),null);for(const mark of ['code','link'])assert.equal(shouldOpenSlashMenu(state(schema.node('paragraph',null,schema.text(' ',[schema.mark(mark)])),1)),null);});
test('选择菜单项后只清理搜索词，保留前后文字和列表结构',()=>{for(const list of [false,true]){const node=list?schema.node('bullet_list',null,schema.node('list_item',null,p('前文 query后文'))):p('前文 query后文');const view={state:state(node,8),dispatch(tr){this.state=this.state.apply(tr);}};const anchor=view.state.selection.from-5;assert.equal(prepareSlashInsertion(view,anchor),true);assert.equal(view.state.doc.textContent,'前文 后文');assert.equal(view.state.selection.$from.parent.content.size,0);if(list)assert.equal(view.state.doc.firstChild.type.name,'bullet_list');}});
test('菜单 API 缺失时允许普通输入',()=>{assert.equal(readSlashMenuApi({}),null);const api={show(){}};assert.equal(readSlashMenuApi({use:()=>({get:()=>api})}),api);});
test('构建补丁匹配当前 Crepe，并在依赖变化时明确失败',async()=>{const source=await readFile(new URL('../node_modules/@milkdown/crepe/lib/esm/index.js',import.meta.url),'utf8');const result=patchCrepeSlashMenu(source);assert.ok(result.includes('textBetween(pos, selection.from'));assert.throws(()=>patchCrepeSlashMenu('changed'));});
